---
abstract: 'Redis protocol parser'
author:
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::CBuilder: 0.27
  ExtUtils::MakeMaker: 6.3002
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
keywords:
  - redis
  - protocol
  - parser
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RedisDB-Parser
no_index:
  directory:
    - t
    - inc
  file:
    - README.pod
requires:
  Encode: 2.1
  Test::More: 0.94
  Try::Tiny: 0
  perl: 5.008004
resources:
  bugtracker: https://github.com/trinitum/perl-RedisDB-Parser/issues
  homepage: https://github.com/trinitum/perl-RedisDB-Parser
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/perl-RedisDB-Parser
version: 2.19_03
x_contributors:
  - 'Pavel Shaydo <zwon@cpan.org>'
